<?php

namespace Survos\DocBundle\Command;

use DavidBadura\MarkdownBuilder\MarkdownBuilder;
use Survos\DocBundle\Service\EntityDocCollector;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Attribute\Option;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Style\SymfonyStyle;
use Symfony\Component\DependencyInjection\Attribute\Autowire;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\Filesystem\Path;
use Symfony\Component\Finder\Finder;

/**
 * One markdown file per entity (fields, relations, and field-bundle metadata —
 * description, group, API/Meili flags — when present) plus an index carrying an
 * inline Mermaid ER diagram of the whole schema, so an agent learns the data
 * model without scanning code.
 */
#[AsCommand('doc:entities', 'Generate agent-friendly markdown docs (with a Mermaid ER diagram) for the entities')]
final class EntityDocsCommand
{
    public function __construct(
        private readonly EntityDocCollector $collector,
        private readonly Filesystem $fs,
        #[Autowire('%kernel.project_dir%')]
        private readonly string $projectDir,
    ) {
    }

    public function __invoke(
        SymfonyStyle $io,
        #[Option('Output directory, relative to project dir unless absolute')]
        string $outputDir = 'docs/entity',
    ): int {
        $entities = $this->collector->collect();
        if ($entities === []) {
            $io->warning('No entities found.');

            return Command::SUCCESS;
        }

        $dir = Path::makeAbsolute($outputDir, $this->projectDir);
        if ($this->fs->exists($dir)) {
            $this->fs->remove((new Finder())->files()->in($dir)->depth(0)->name('*.md'));
        }

        $generatedAt = (new \DateTimeImmutable())->format(DATE_ATOM);
        foreach ($entities as $entity) {
            $this->fs->dumpFile($dir . '/' . $entity['short'] . '.md', $this->renderEntity($entity, $generatedAt));
        }
        $this->fs->dumpFile($dir . '/README.md', $this->renderIndex($entities, $generatedAt));

        $io->success(sprintf('%d entity file(s) written to %s', count($entities), $dir));

        return Command::SUCCESS;
    }

    /**
     * @param array<string, mixed> $entity
     */
    private function renderEntity(array $entity, string $generatedAt): string
    {
        $md = new MarkdownBuilder();
        $md->h1($entity['short']);

        if (is_string($entity['description']) && $entity['description'] !== '') {
            $md->p($entity['description']);
        } elseif (is_string($entity['label']) && $entity['label'] !== '') {
            $md->p($entity['label']);
        }

        $md->p($md->inlineItalic(sprintf(
            'Generated by `doc:entities` on `%s`. Class `%s`, table `%s`.',
            $generatedAt,
            $entity['class'],
            $entity['table']
        )));

        $facts = [];
        if (is_string($entity['group']) && $entity['group'] !== '') {
            $facts[] = 'group ' . $md->inlineCode($entity['group']);
        }
        if ($entity['api']) {
            $facts[] = 'API Platform';
        }
        if ($entity['meili']) {
            $facts[] = 'Meilisearch';
        }
        if ($facts !== []) {
            $md->p(implode(' · ', $facts));
        }

        $md->h2('Fields');
        $rows = [];
        foreach ($entity['fields'] as $field) {
            $rows[] = [
                $md->inlineCode($field['name']) . ($field['pk'] ? ' (PK)' : ''),
                $md->inlineCode($field['type']),
                $field['nullable'] ? 'yes' : 'no',
            ];
        }
        $md->table(['Field', 'Type', 'Nullable'], $rows)->br();

        if ($entity['relations'] !== []) {
            $md->h2('Relations');
            $items = [];
            foreach ($entity['relations'] as $relation) {
                $items[] = sprintf(
                    '%s → %s (%s)',
                    $md->inlineCode($relation['name']),
                    $md->inlineCode($relation['target']),
                    $relation['toMany'] ? 'collection' : 'single'
                );
            }
            $md->bulletedList($items);
        }

        return $md->getMarkdown();
    }

    /**
     * @param list<array<string, mixed>> $entities
     */
    private function renderIndex(array $entities, string $generatedAt): string
    {
        $md = new MarkdownBuilder();
        $md->h1('Entities');
        $md->p($md->inlineItalic(sprintf('Generated by `doc:entities` on `%s`. One file per entity.', $generatedAt)));

        $md->h2('Schema');
        $md->code($this->collector->mermaid($entities), 'mermaid');

        $md->h2('Entities');
        $items = [];
        foreach ($entities as $entity) {
            $line = $md->inlineLink($entity['short'] . '.md', $md->inlineCode($entity['short']));
            $summary = $entity['description'] ?? $entity['label'];
            if (is_string($summary) && $summary !== '') {
                $line .= ' — ' . $summary;
            }
            $items[] = $line;
        }
        $md->bulletedList($items);

        return $md->getMarkdown();
    }
}
